### PR TITLE
Fixes #188 - Implement loading animation on trust.mybit.io

### PR DESCRIPTION
**Pull request by yossipik**
Fixes https://github.com/MyBitFoundation/MyBit-Network.tech/issues/188

mybit-trust

### CODE REVIEW

**Comment by 0xjjpa** [comment]
Hi @yossipik , this might take a bit to solve as we have to setup CI/CD on this repo, and connect the bounty to this repository as well, but bear with us!

**Comment by yossipik** [comment]
Hi @jjperezaguinaga, thanks for the heads-up. 
Actually, I did not manage to connect the bounty. How should I do that?

> Hi @yossipik , this might take a bit to solve as we have to setup CI/CD on this repo, and connect the bounty to this repository as well, but bear with us!

**Comment by 0xjjpa** [comment]
@yossipik Unfortunately for the time being, you need to create pull-request within the https://github.com/MyBitFoundation/MyBit-Network.tech repository that's empty and write "Fixes #188" from there otherwise it won't be picked up by Open Bounty

**Comment by 0xjjpa** [comment]
@yossipik Could you add an empty commit to trigger our CI/CD setup?

**Comment by yossipik** [comment]
@jjperezaguinaga Build failed but I don't think it is related to my code. Please advise.

**Comment by 0xjjpa** [comment]
@yossipik It's missing the configuration that was added to the branch recently. Just sent you a [Pull Request](https://github.com/yossipik/MyBit-Trust.website/pull/1), for more real-time answers feel free to drop by our [Gitter room](https://gitter.im/Mybit-Foundation/DDF).

**Review by 0xjjpa — APPROVED** [review]
✅

**Pull request merged**
